#!/usr/bin/env python3


import pyautogui
from i3ipc import Connection, Event
import sys

i3 = Connection()
SCREEN_WIDTH, SCREEN_HEIGHT = pyautogui.size()
WINDOW_WIDTH = str(int(float(SCREEN_WIDTH) * float(sys.argv[1]) * 0.01))
WINDOW_HEIGHT = str(int(float(SCREEN_HEIGHT) * float(sys.argv[2]) * 0.01))
WINDOW_COMMAND = 'resize set ' + WINDOW_WIDTH + ' ' + WINDOW_HEIGHT + ', move absolute position center'


def window_resize(i3, event):
    event.container.command(WINDOW_COMMAND)


# Float windows manually, but center and size as
# a proportion of screen resolution.
i3.on('window::floating', window_resize)

i3.main()
